# ------------------------------
# .pre-commit-config.yaml
# ------------------------------
# Pre-commit configuration file that defines hooks
# for linting, formatting, and security scanning.

repos:
  # -------------------------------------------
  # 1. Basic file checks: YAML, TOML, EOF, whitespace
  # -------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
       - id: check-yaml              # check YAML file validity
       - id: check-toml              # check TOML file validity
       - id: end-of-file-fixer       # ensure files end with a newline
       - id: trailing-whitespace     # remove trailing whitespace


  # -------------------------------------------
  # 2. Import sorting
  # -------------------------------------------
  - repo: https://github.com/PyCQA/isort.git
    rev: 7.0.0
    hooks:
      - id: isort

  # -------------------------------------------
  # 3. AutoPEP8 formatter
  # -------------------------------------------
  - repo: https://github.com/hhatto/autopep8.git
    rev: v2.3.2
    hooks:
      - id: autopep8

  # -------------------------------------------
  # 4. Black code formatter
  # -------------------------------------------
  - repo: https://github.com/psf/black.git
    rev: 25.11.0   #your code here
    hooks:
      - id: black   #your code here

  # -------------------------------------------
  # 5. Linting with Flake8
  # -------------------------------------------
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.3.0  #your code here
    hooks:
      - id: flake8   #your code here
        args: ["--extend-ignore=E501"]

  # -------------------------------------------
  # 6. Ruff linter and formatter (fast Python tool)
  # -------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.14.6   #your code here
    hooks:
      - id: ruff     #your code here     # run Ruff lint
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff     #your code here       # run Ruff format
        types_or: [python, pyi]
        args: [--fix]

  # -------------------------------------------
  # 7. Secret scanning / security (Gitleaks)
  # -------------------------------------------
  - repo: https://github.com/gitleaks/gitleaks.git
    rev: v8.29.1    #your code here
    hooks:
      - id: gitleaks    #your code here
